---
title: "Overview record of the AgeAndSPVL project"
output:
  html_document:
    df_print: paged
    theme: cosmo
    css: tablestyle.css
  pdf_document: default
  word_document: default
---

### August 4, 2018

The project was begun in late January and early February, 2018, but then progress was halted again until late July. Steve set up a Github repository back in February, but did not commit most of the files from that period until just now. The early period was also highly exploratory, with no documentation.  This is an attempt to document and standardize the work so far and then document all subsequent work moving forward.

Original questions:

Steve asked: It has been observed that SPVL increases with age at seroconversion, although it is not well understood why. Given the results of the role paper, when EI men had higher mSPVL than ER/RV men because of the higher selective pressure caused by the narrowed transmission bottleneck, he hypotehsized that perhaps something similar is going on with age.  That is, older people have less opportunity for acquisition on average (fewer acts and/or partners), so that those who did get infected would do so with higher SPVL. Indeed, the fact that people are generally assortative by age seemed like it could magnify this effect, in contrast to the role effect where the alternating chains of infection (I->R->I->R) kept the two from diverging too far.

When Steve brought up looking at age and SPVL, John had a different question: do populations in which the risk is heavily concentrated in young people have overall higher mSPVL than populations with the same overall amount of risk but spread out more over the lifecourse?

Steve began by exploring some small, simple scenarios with just a single replicate in order to get some intution.  So far, there have been 10, which are stored in files ageSPVL_explore_mXX where XX = 01 to 10. These are then compiled and analyzed in the file ageSPVL_explore_meta.

Parameters looked at so far are:

Run | 1	| 2	| 3	| 4	| 5	| 6	| 7	| 8	| 9	| 10
---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- 
min age	| 18 | 18 | 18 | 18 | 18 | 18 | 18 | 18 | 18 | 18
maxage | 55 | 55 | 55 | 55 | 55 | 55 | 55 | 55 | 55 | 55
mean_sqrtage_diff | 0.3 | 0.3 | 0.3 | 0.3 | 0.3 | 0.3 | 1 | 1.5 | 2 | 0.6
mean_sex_acts_per_day | 0.2 | --- | --- | --- | --- | --- | --- | --- | --- | ---
prob_sex_by_age | F | T | T | T | T | T | T | T | T | T
prob_sex_age_19 | --- | 0.4 | 0.3 | 0.2 | 0.4 | 0.4 | 0.3 | 0.3 | 0.3 | 0.3
max_age_sex | --- | 55 | 55 | 55 | 35 | 55 | 55 | 55 | 55 | 35
relation_dur | 50 | 50 | 50 | 50 | 50 | 200 | 50 | 50 | 50 | 50

Some basic insights:

```{R}
setwd("../")
nruns <- 10
popatts <- popsumm <- list()

agecoef <- iSPVL <- ageinf <- prev <- numinc <- agematch <- rep(NA, nruns)

for (i in 1:nruns) {
  if(i<10) filler <- "0" else filler <- ""
  load(paste("ageSPVL_m",filler,i,".rda",sep=""))
  obj <- get(paste("ageSPVL_m",filler,i,sep=""))
  popatts[[i]] <- obj$pop[[1]]
  popsumm[[i]] <- get(paste("ageSPVL_m",filler,i,sep=""))$popsumm[[1]]
  agecoef[i] <- lm(log(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0],10)~
               popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0])$coef[[2]]
  iSPVL[i] <- mean(log10(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0]),na.rm=TRUE)
  ageinf[i] <- mean(popatts[[i]]$age_infection,na.rm=TRUE)
  prev[i] <- tail(popsumm[[i]]$prevalence,1)
  numinc[i] <- sum(popatts[[i]]$Time_Inf>0, na.rm=TRUE)
  agematch[i] <- obj$nwparam[[1]]$coef.form['absdiff.sqrt_age']
}

plot(numinc, prev)
plot(prev, iSPVL, type='b')
plot(agecoef); abline(h=0)
plot(agematch)
```

So some insights here:

- Incidence and prevalence are nearly perfectly correlated (no surprise, just a good check).

- mean dquare root age difference of 1 is about what is epected by change for this set of models.

- prevalence generally predicts average SPVL.  However, runs 8, 9 and 10 generally lie above this.  Runs 8 and 9 are actually the cases that had disassortative mixing by age (bigger difference than expected by chance).  And 10 concentrates the sex at younger ages and has moderate assortativity by age. So now we're getting somewhere.

- The only cases where the coefficient on SPVL~age is positive are the ones where there is disassortative mixing by age.  The others are the reverse.  This is very very strange and requires much probing.

Some thoughts Steve has: perhaps these runs are far from equilibrium.  Do getting infected younger mean getting infected later in the simulation on average, and there is a secular trend in SPVL increasing overall?

This also raises the question of whether this paper should also think about trends in SPVL over the course of the epidemic finally.

Next step: run regression with date of infection and age of infection to see what happens.

### Aug 6, 2018

Ran the regression with date infected as well:

```{R}
agecoef2 <- rep(NA, nruns)

for (i in 1:nruns) {
  agecoef2[i] <- lm(log(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0],10)~
    popatts[[i]]$Time_Inf[popatts[[i]]$Time_Inf>0]+
    popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0])$coef[[3]]
}
plot(agecoef2)

```

Also, curious to confirm the ages at which infection is occuring:

```{R, out.width="20%"}

meanageinf <- rep(NA,10)
for (i in 1:nruns) {
    hist(popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0],main="",
        breaks=c(15,20,25,30,35,40,45,50,55,60))
    meanageinf[i] <- mean(popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0], na.rm=TRUE)
}

```

### Aug 8, 2018

Removed agePSVL-explore_meta.R because I've realized that it is redundant with this document -- the code resides here as a living document.

The distribution of ages at infection in runs 1 through 10 show that only runs 8 and 9 have a sizeable number of people getting infected at older ages. And they're the two with SPVL increasing with age.  They're also the two that have age-discordant mixing.  But maybe it's not the age-discordant mixing per se that creates the positive age/SPVL effect -- maybe it's just having some  older infections.  So some new runs:

Run | 11 | 12 | 13
---- | ---- | ----
min age	| 18 | 18 | 18
maxage | 55 | 55 | 55
mean_sqrtage_diff | 0.6 | 0.6 | 0.6
mean_sex_acts_per_day | --- | --- | ---
prob_sex_by_age | T | T | T
prob_sex_age_19 | 0.2 | 0.2 | 0.2
max_age_sex | 55 | 55 | 55
relation_dur | 50 | 100 | 200

```{R}
setwd("../")
for (i in 11:13) {
  if(i<10) filler <- "0" else filler <- ""
  load(paste("ageSPVL_m",filler,i,".rda",sep=""))
  obj <- get(paste("ageSPVL_m",filler,i,sep=""))
  popatts[[i]] <- obj$pop[[1]]
  popsumm[[i]] <- get(paste("ageSPVL_m",filler,i,sep=""))$popsumm[[1]]
  agecoef[i] <- lm(log(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0],10)~
               popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0])$coef[[2]]
  iSPVL[i] <- mean(log10(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0]),na.rm=TRUE)
  ageinf[i] <- mean(popatts[[i]]$age_infection,na.rm=TRUE)
  prev[i] <- tail(popsumm[[i]]$prevalence,1)
  numinc[i] <- sum(popatts[[i]]$Time_Inf>0, na.rm=TRUE)
  agematch[i] <- obj$nwparam[[1]]$coef.form['absdiff.sqrt_age']
  meanageinf[i] <- mean(popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0], na.rm=TRUE)
}

plot(numinc, prev)
plot(prev, iSPVL, type='b')
plot(agecoef); abline(h=0)
plot(agematch)
```

So run 12 is maybe above?  Which is odd - it's not monotonoic (or it's just stochastic).

Let's look at mean age infected as a summar stat on the age dist:

```{R}
plot(meanageinf, agecoef)
```

Let's redo 11-13 as 14-16 with higher overall incidence so that we can have more data:


Run | 14 | 15 | 16
---- | ---- | ---- | ----
min age	| 18 | 18 | 18
maxage | 55 | 55 | 55
mean_sqrtage_diff | 0.6 | 0.6 | 0.6
mean_sex_acts_per_day | --- | --- | ---
prob_sex_by_age | T | T | T
prob_sex_age_19 | 0.3 | 0.3 | 0.3
max_age_sex | 55 | 55 | 55
relation_dur | 50 | 100 | 200

```{R}
setwd("../")
for (i in 14:16) {
  if(i<10) filler <- "0" else filler <- ""
  load(paste("ageSPVL_m",filler,i,".rda",sep=""))
  obj <- get(paste("ageSPVL_m",filler,i,sep=""))
  popatts[[i]] <- obj$pop[[1]]
  popsumm[[i]] <- get(paste("ageSPVL_m",filler,i,sep=""))$popsumm[[1]]
  agecoef[i] <- lm(log(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0],10)~
               popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0])$coef[[2]]
  iSPVL[i] <- mean(log10(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0]),na.rm=TRUE)
  ageinf[i] <- mean(popatts[[i]]$age_infection,na.rm=TRUE)
  prev[i] <- tail(popsumm[[i]]$prevalence,1)
  numinc[i] <- sum(popatts[[i]]$Time_Inf>0, na.rm=TRUE)
  agematch[i] <- obj$nwparam[[1]]$coef.form['absdiff.sqrt_age']
  meanageinf[i] <- mean(popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0], na.rm=TRUE)
}

plot(numinc, prev)
plot(prev, iSPVL, type='b')
plot(agecoef); abline(h=0)
plot(agematch)
plot(meanageinf)
plot(meanageinf, agecoef, type='b')
plot(meanageinf, iSPVL)
```

The evidence for John's hypothesis is beginning to accumulate.
For Steve's, not so much.

Steve is pondering more. Is older age really like being insertive?  That is, insertive guys have as many partners and exposures as receptive guys do (actually, more exposures given higher prevalence in their partner pool); but they have lower probability of acquisition per act.  We're odeling older people as having fewer acts than others.  Is that really an analogous mechanism? 

Let's dive deeper into two runs, 12 and 15:

```{R}
p12 <- popatts[[12]]
p15 <- popatts[[15]]
plot(p12$age_infection, p12$Donors_age)
plot(p15$age_infection, p15$Donors_age)
plot(p12$Donors_age, p12$Donors_LogSetPoint)
plot(p15$Donors_age, p15$Donors_LogSetPoint)
```

Aha. Steve has a sudden realization, of something that he thinks Sarah actually hypothesized back in Feb/Mar, but which he fogot about until now.

Because there is no treatment, people with high SPVL die quickly.  With assortatice age mixing, older folks mostly get infected by other older folks, but most of the folks with high SPVL have died before they reach older age.  So there are two different effects operating here in different directions.

The trick will be to add treatment into the model, in ways that make it so that when treatment fails they go back up to the SPVL they would have in the absence of treatment.

So, things Steve needs to figure out:
(1) how do the VL dynamics work in the presence of treatment
(2) also - how does the prob_sex_by_age / prob_sex_age_19  / max_age_sex code work exactly?  Why can't max_age_sex be > 55?

Steve is also thinking about an additional analysis: if one has heterosexual asymmetric age mixing (a la absdiffby) does that lead to higher mSPVL for women, even after controlling for age at infection?  This could be an interesting analysis, but also requires understanding the lit on sex differences in SPVL a bit more - does it appear in setting with tx, without tx, or both?

OK, as an experiment, trying a version in which the risk is concentrated exclusively in a 10-year period, but still hwere risk declines over that period. These folks shouldn't see much die-off among partners.  Let's see....

Run | 17 | 18 | 19
---- | ---- | ---- | ----
min age	| 18 | 18 | 18
maxage | 55 | 55 | 55
mean_sqrtage_diff | 0.6 | 0.6 | 0.6
mean_sex_acts_per_day | --- | --- | ---
prob_sex_by_age | T | T | T
prob_sex_age_19 | 1 | 1 | 1
max_age_sex | 29 | 29 | 29
relation_dur | 50 | 100 | 200


```{R}
setwd("../")
for (i in 17:19) {
  if(i<10) filler <- "0" else filler <- ""
  load(paste("ageSPVL_m",filler,i,".rda",sep=""))
  obj <- get(paste("ageSPVL_m",filler,i,sep=""))
  popatts[[i]] <- obj$pop[[1]]
  popsumm[[i]] <- get(paste("ageSPVL_m",filler,i,sep=""))$popsumm[[1]]
  agecoef[i] <- lm(log(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0],10)~
               popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0])$coef[[2]]
  iSPVL[i] <- mean(log10(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0]),na.rm=TRUE)
  ageinf[i] <- mean(popatts[[i]]$age_infection,na.rm=TRUE)
  prev[i] <- tail(popsumm[[i]]$prevalence,1)
  numinc[i] <- sum(popatts[[i]]$Time_Inf>0, na.rm=TRUE)
  agematch[i] <- obj$nwparam[[1]]$coef.form['absdiff.sqrt_age']
  meanageinf[i] <- mean(popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0], na.rm=TRUE)
}

plot(numinc, prev)
plot(prev, iSPVL, type='b')
plot(agecoef); abline(h=0)
plot(agematch)
plot(meanageinf)
plot(meanageinf, agecoef, type='b')
plot(meanageinf, iSPVL)
```


```{R}
i <- 17
summary(lm(log(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0],10)~
               popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0]))
```

```{R}
for (i in 17:19) {
    hist(popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0],main="",
        breaks=17:65)
}
```

```{R}

plot(popatts[[17]]$age_infection[popatts[[i]]$Time_Inf>0],
     popatts[[17]]$LogSetPoint[popatts[[i]]$Time_Inf>0]
     
       )
```

```{R}
i <- 17
summary(lm(log(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0 & popatts[[i]]$age_infection<30],10)~
               popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0 & popatts[[i]]$age_infection<30]))
```

### Aug 9, 2018

I have learned from John and James that they have code to model tx cessation and VL rebound. Hurray! Will try some runs right now.

Run | 20 
---- | ---- 
min age	| 18 
maxage | 55 
mean_sqrtage_diff | 0.6 
mean_sex_acts_per_day | --- 
prob_sex_by_age | T 
prob_sex_age_19 | 0.4 
max_age_sex | 55 
relation_dur | 200
tx_type | "random"
mean_trtmnt_delay | 1
start_treatment_campaign | 1
proportion_treated | 0.5
testing_model | "interval"
mean_test_interval_male | 365
prob_tx_dropout | 0.1
  

```{R}
setwd("../")
for (i in 20:21) {
  if(i<10) filler <- "0" else filler <- ""
  load(paste("ageSPVL_m",filler,i,".rda",sep=""))
  obj <- get(paste("ageSPVL_m",filler,i,sep=""))
  popatts[[i]] <- obj$pop[[1]]
  popsumm[[i]] <- get(paste("ageSPVL_m",filler,i,sep=""))$popsumm[[1]]
  agecoef[i] <- lm(log(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0],10)~
               popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0])$coef[[2]]
  iSPVL[i] <- mean(log10(popatts[[i]]$SetPoint[popatts[[i]]$Time_Inf>0]),na.rm=TRUE)
  ageinf[i] <- mean(popatts[[i]]$age_infection,na.rm=TRUE)
  prev[i] <- tail(popsumm[[i]]$prevalence,1)
  numinc[i] <- sum(popatts[[i]]$Time_Inf>0, na.rm=TRUE)
  agematch[i] <- obj$nwparam[[1]]$coef.form['absdiff.sqrt_age']
  meanageinf[i] <- mean(popatts[[i]]$age_infection[popatts[[i]]$Time_Inf>0], na.rm=TRUE)
}

plot(numinc, prev)
plot(prev, iSPVL, type='b')
plot(agecoef); abline(h=0)
plot(agematch)
plot(meanageinf)
plot(meanageinf, agecoef, type='b')
plot(meanageinf, iSPVL)

```

Exploring whether the VL code works:

```{R}
plot(log10(ageSPVL_m21$vl_list[[1]][[7200]][,'vl']))
#plot_vl_trajectories(ageSPVL_m21, outpath = ".", name="m21")

```

